name: test_08

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pylint pytest-cov pylint-exit
    - name: Analysing the code with pylint
      run: |
        pylint 08/test_project/ --disable=C0111 || pylint-exit $?
    - name: Test the code with pytest
      run: |
        pytest --cov=test_project --cov-fail-under=90 --cov-branch 08/test_project/