name: test_08

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pip install pylint
        pylint 08/test_project/ --disable=C0111
      continue-on-error: true
    - name: Test the code with pytest
      run: |
        pip install pytest-cov
        pytest --cov=test_project --cov-fail-under=90 --cov-branch 08/test_project/